# Generated by Django 2.0.2 on 2018-03-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogooders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=3000000)),
                ('last_name', models.CharField(max_length=3000000)),
            ],
        ),
        migrations.CreateModel(
            name='Samaritans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=3000000)),
            ],
        ),
    ]
