# Generated by Django 2.0.2 on 2018-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALittleGift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.CharField(max_length=30000),
        ),
    ]
