# Generated by Django 2.0.2 on 2018-03-11 11:01

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ALittleGift', '0002_auto_20180311_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='location',
            field=geoposition.fields.GeopositionField(default=(52.522906, 13.41156), max_length=42),
            preserve_default=False,
        ),
    ]
